### PR TITLE
docs: Update of YAML file with newly added endpoints

### LINKED ISSUE #318: Required to update `lpvs-api.yaml` file
https://github.com/Samsung/LPVS/blob/main/doc/lpvs-api.yaml file has outdated content.
We need to update the file with the description of new endpoints.

### PR DESCRIPTION
**Pull request by o-kopysov**
# Description

Updated YAML file with API. Validated at https://jsonformatter.org/yaml-validator
Also, PR includes minor fixes in the documentation.

Fixes #318 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Code cleanup/refactoring
- [X] Documentation update
- [X] This change requires a documentation update
- [ ] CI system update
- [ ] Test Coverage update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by o-kopysov** [comment]
JaCoCo Test Coverage Summary
Coverage: 93.257%
Branches: 80.943%

**Review by tiokim — APPROVED** [review]
LGTM

**Review by m-rudyk — APPROVED** [review]
Approved

**Review by o-konoval — APPROVED** [review]
+1

**Pull request merged**
