### PR TITLE
test: Add unit tests for "main" function

### PR DESCRIPTION
**Pull request by o-kopysov**
# Pull Request

## Description

Improve code coverage for "main" function of the LPVS service. 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code cleanup/refactoring
- [ ] Documentation update
- [ ] This change requires a documentation update
- [ ] CI system update
- [X] Test Coverage update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

**Test Configuration**:
* Java: v17
* LPVS Release: v1.5.1

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] My code meets the required code coverage for lines (90% and above)
- [X] My code meets the required code coverage for branches (80% and above)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by o-kopysov** [comment]
@tdrozdovsky, please check whether there is any influence on the functional tests produced by my changes. Thanks!

**Review by m-rudyk — APPROVED** [review]
I have no objection, approved.

**Review by t-naumenko — APPROVED** [review]
LGTM
More tests - great!

**Review by o-konoval — APPROVED** [review]
LGTM

**Comment by t-naumenko** [comment]
> @tdrozdovsky, please check whether there is any influence on the functional tests produced by my changes. Thanks!

Functional tests were successfully passed

**Review by tdrozdovsky — APPROVED** [review]

**Pull request merged**
