### PR TITLE
fix: Update github->action javadoc permissions

### PR DESCRIPTION
**Pull request by tdrozdovsky**
# Description

fix permissions for github->action

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] CI system update

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by o-konoval — APPROVED** [review]
LGTM

**Review by o-kopysov — CHANGES_REQUESTED** [review]
@tdrozdovsky please add top level permissions

**Review by o-kopysov — APPROVED** [review]
+1

**Comment by o-kopysov** [comment]
Fix for security issue.

**Pull request merged**
