### PR TITLE
Change to the pom.xml file to allow usage as a library

### PR DESCRIPTION
**Pull request by v-kerimov**
# Description

Implements change to pom.xml to build project in such a way so that class files are placed at the root of the JAR, which enables use of the built package as a dependency in other projects.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code cleanup/refactoring
- [ ] Documentation update
- [ ] This change requires a documentation update
- [ ] CI system update
- [ ] Test Coverage update

# How Has This Been Tested?
All unit tests were not touched and still pass.

**Test Configuration**:
* Java: v11
* LPVS Release: v1.1.0

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by o-kopysov** [comment]
@v-kerimov  Please provide a full description of the current PR.

**Comment by v-kerimov** [comment]
> @v-kerimov Please provide a full description of the current PR.

done.

**Review by m-rudyk — APPROVED** [review]
Approved.

**Review by o-kopysov — APPROVED** [review]
LGTM

**Pull request merged**
