### PR TITLE
Update security doc

### PR DESCRIPTION
**Pull request by tdrozdovsky**
# Description

Update security doc 

## Type of change

- [x] Documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by o-kopysov — APPROVED** [review]
+1

**Review by o-konoval — COMMENTED** [review]
Good job. Unfortunately can`t see tables itself for checking - only UML code. Needed to see code on UML viewer?

**Comment by tdrozdovsky** [comment]
> Good job. Unfortunately can`t see tables itself for checking - only UML code. Needed to see code on UML viewer?
 Please install PlantUML extension to your browser

**Review by o-konoval — APPROVED** [review]
Thanks for information of extension. Now it rendered. Looks fine.Approved.

**Review by m-rudyk — APPROVED** [review]
Approved

**Pull request merged**
