### PR TITLE
Masking the key for addressing the vulnerability

### PR DESCRIPTION
**Pull request by MoonkiHong**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Addressing the vulnerability report from the community member.
- Masking the root password for the sample SQL DB access.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code cleanup/refactoring
- [ ] Documentation update
- [ ] This change requires a documentation update
- [ ] CI system update
- [ ] Test Coverage update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. Below is just an example and you can delete it when you contribute.

**Test Configuration**:
* Java: v11
* LPVS Release: v1.x.x

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by daraeahn — APPROVED** [review]

**Review by junmin-kim — APPROVED** [review]
LGTM

**Review by o-kopysov — APPROVED** [review]
@MoonkiHong  I thought that we have to clean all the commit history to resolve this issue. If my understanding was wrong, I have no objections regarding this PR.

**Comment by MoonkiHong** [comment]
> @MoonkiHong I thought that we have to clean all the commit history to resolve this issue. If my understanding was wrong, I have no objections regarding this PR.

Agreed. Please clean the regarding commit history as well.

**Comment by o-kopysov** [comment]
@MoonkiHong  repository has been updated. History is clean now.

**Pull request merged**
