### PR TITLE
Release v1.0.2 draft

### PR DESCRIPTION
**Pull request by o-kopysov**
# Description

Prepared the update for the source code for LPVS 1.0.2 release.
Changes include support of DB to store scan results, logging updates, UT update, etc.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Code cleanup/refactoring
- [X] Documentation update
- [X] This change requires a documentation update
- [ ] CI system update
- [X] Test Coverage update

# How Has This Been Tested?
Same way as usually

**Test Configuration**:
* Java: v11
* LPVS Release: v1.0.2

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tiokim** [comment]
Can you separate and open PRs in terms of features or bugs? It is hard to review dump changes.
Also, LPVS should be guaranteed to be run regardless of the presence of DB like v1.0.1.

**Comment by o-kopysov** [comment]
@tiokim  It's hard to separate this PR into several PRs because it contains the introduction of DB into LPVS project - adding a lot of entity classes, updating the source code of services, fix of UTs. Also, the target branch for this PR is `db-support`, not `main`. So, LPVS release v1.0.2 will be done from `db-support` branch,

**Comment by MoonkiHong** [comment]
@o-kopysov Can you rectify more in detail on this PR, so that we at least can be more easily take a look at overall 52 files in the territory of this PR. 🙏

**Review by tiokim — APPROVED** [review]
> @tiokim It's hard to separate this PR into several PRs because it contains the introduction of DB into LPVS project - adding a lot of entity classes, updating the source code of services, fix of UTs. Also, the target branch for this PR is `db-support`, not `main`. So, LPVS release v1.0.2 will be done from `db-support` branch,

I agree that this PR is only for `db-support` branch for dev purpose. Please do not include other functionalities except database to `db-support` branch. 

I hope you will open next PR that can operate LPVS without database.

**Comment by o-kopysov** [comment]
> @o-kopysov Can you rectify more in detail on this PR, so that we at least can be more easily take a look at overall 52 files in the territory of this PR, especially in the PR description. 🙏

I will provide more details in the PR to `main` branch.

**Pull request merged**
