### PR TITLE
Add external LPVS API description

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

Add a description of the external LPVS API

image

## Type of change

- [x] Documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by o-kopysov — APPROVED** [review]
+1

**Review by t25kim — APPROVED** [review]
It would be great if it contains the [X-Hub-Signature-256](https://github.com/Samsung/LPVS/blob/f92b77ea54daccaee4c595b3d4ce7d14a7697a2b/src/main/java/com/lpvs/controller/GitHubWebhooksController.java#L43) header information.

**Review by MoonkiHong — APPROVED** [review]
+1

**Comment by tdrozdovsky** [comment]
> It would be great if it contains the [X-Hub-Signature-256](https://github.com/Samsung/LPVS/blob/f92b77ea54daccaee4c595b3d4ce7d14a7697a2b/src/main/java/com/lpvs/controller/GitHubWebhooksController.java#L43) header information.

Done!

image

**Pull request merged**
