### PR TITLE
Add java format checker to github Actions

### PR DESCRIPTION
**Pull request by tdrozdovsky**
# Description

You need to add a checker to match the style code

## Type of change

- [x] Code cleanup/refactoring

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. Below is just an example and you can delete it when you contribute.

See github->actions 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by tiokim — COMMENTED** [review]
What about using AOSP style (4-space indentation)?

**Comment by tdrozdovsky** [comment]
> What about using AOSP style (4-space indentation)?

Done!

**Review by o-kopysov — APPROVED** [review]
LGTM

**Review by tiokim — APPROVED** [review]
LGTM

**Pull request merged**
