### PR TITLE
fix: Change CrudRepository to JpaRepository for 2 repos

### PR DESCRIPTION
**Pull request by o-kopysov**
# Description

Fix to follow one style for all repositories in LPVS.
image

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Code cleanup/refactoring
- [ ] Documentation update
- [ ] This change requires a documentation update
- [ ] CI system update
- [ ] Test Coverage update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by tdrozdovsky — APPROVED** [review]

**Review by v-kerimov — APPROVED** [review]
Inessential change but if it helps this repo comply with something, good.

**Review by o-konoval — APPROVED** [review]
LGTM

**Review by m-rudyk — APPROVED** [review]
Approved

**Review by tiokim — APPROVED** [review]
LGTM

**Pull request merged**
