### PR TITLE
docs: add repository map reference to README.md

### PR DESCRIPTION
**Pull request by alexkarezin**
# Description

Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/samsunglpvs/). Built directly from source and updated on schedule. Intended to simplify developer's introduction to the project. In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful.

## Type of change

- [x] Documentation update

# How Has This Been Tested?

No functionality impact. Documentation-only changes.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by o-kopysov** [comment]
@alexkarezin  On the page "Module Dependencies" I see the error log 
https://sourcespy.com/github/samsunglpvs/xx-mdependencies-.html
Do you know how we can fix this issue?

**Comment by alexkarezin** [comment]
@o-kopysov  ...that's quite embarrassing (my oversight). I'll make sure to have this addressed today.

**Comment by alexkarezin** [comment]
The page was pointing to a module diagram without module context. The issue has been addressed. Thank you for your consideration!

**Review by tiokim — APPROVED** [review]
LGTM!

**Review by MoonkiHong — APPROVED** [review]
+1

**Review by o-kopysov — APPROVED** [review]
+1

**Pull request merged**
