### PR TITLE
fix: Update scanoss dependencies

### LINKED ISSUE #489: Error occurs during the operation of the _scanoss_
## Bug Report

**Description:**

Need to update the dependencies for the _scanoss_. Since an error occurs during the operation of the _scanoss_

**Screenshots:**
```sh
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    crc32c==2.3.post0 from https://files.pythonhosted.org/packages/a1/10/2c6080f1944e14a70e95e6444cd279dc78a328d59d8f398fddb2b6f1f96e/crc32c-2.3.post0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=e0925a7a8fcc216744e86c21f1749c22f950f9bdad512cb5c80ee85017625bd5 (from -r requirements.txt (line 4)):
        Expected sha256 a2f6105a430f4f1f393cc660bf8ac3a4860396fa9b5ac8bf0c7ba1de044a3cbc
             Got        e0925a7a8fcc216744e86c21f1749c22f950f9bdad512cb5c80ee85017625bd5

    cffi==1.15.1 from https://files.pythonhosted.org/packages/b7/8b/06f30caa03b5b3ac006de4f93478dbd0239e2a16566d81a106c322dc4f79/cffi-1.15.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=4f2c9f67e9821cad2e5f480bc8d83b8742896f1242dba247911072d4fa94c192 (from -r requirements.txt (line 17)):
        Expected sha256 5d598b938678ebf3c67377cdd45e09d431369c3b1a5b331058c338e201f12b27
             Got        4f2c9f67e9821cad2e5f480bc8d83b8742896f1242dba247911072d4fa94c192

    dukpy==0.3.0 from https://files.pythonhosted.org/packages/86/55/db5045cf844c38fdd25985555d337645ded33ef58fde78a3e5cb09fe4e8a/dukpy-0.3.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=2feb5c2d05b3c9b8fafc9088c5c025a14c9e239f96abb1aa75ebc022f1777e9c (from -r requirements.txt (line 20)):
        Expected sha256 9087a3321649beb17f91afa6ffde991d477aa0029c3be5ce908369517ac85251
             Got        2feb5c2d05b3c9b8fafc9088c5c025a14c9e239f96abb1aa75ebc022f1777e9c

    charset-normalizer==3.1.0 from https://files.pythonhosted.org/packages/74/5f/361202de730532028458b729781b8435f320e31a622c27f30e25eec80513/charset_normalizer-3.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=de5695a6f1d8340b12a5d6d4484290ee74d61e467c39ff03b39e30df62cf83a0 (from -r requirements.txt (line 29)):
        Expected sha256 21fa558996782fc226b529fdd2ed7866c2c6ec91cee82735c98a197fae39f706
             Got        de5695a6f1d8340b12a5d6d4484290ee74d61e467c39ff03b39e30df62cf83a0
```

**Test Environment Configuration:**
Please complete the following information):
* Java: OpenJDK 17, scanoss 1.8.0
* LPVS Release: 1.4.2

### PR DESCRIPTION
**Pull request by tdrozdovsky**
# Pull Request

## Description

Update the dependencies for the scanoss. Since an error occurs during the operation of the scanoss
Fixes #489 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**Test Configuration**:
* Java: v17
* LPVS Release: v1.4.2

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] My code meets the required code coverage for lines (90% and above)
- [x] My code meets the required code coverage for branches (80% and above)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by o-konoval — APPROVED** [review]
Update dependencies. Approved.

**Comment by o-kopysov** [comment]
@tdrozdovsky 
```
1.553 ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
1.553     crc32c==2.3.post0 from https://files.pythonhosted.org/packages/56/70/9bc4e4b676472af3c052d81a3e8b83fe72bf75f37d4d3a1fa226588521a7/crc32c-2.3.post0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=a2f6105a430f4f1f393cc660bf8ac3a4860396fa9b5ac8bf0c7ba1de044a3cbc (from -r requirements.txt (line 4)):
1.553         Expected sha256 e0925a7a8fcc216744e86c21f1749c22f950f9bdad512cb5c80ee85017625bd5
1.553              Got        a2f6105a430f4f1f393cc660bf8ac3a4860396fa9b5ac8bf0c7ba1de044a3cbc
```

**Review by t-naumenko — COMMENTED** [review]
Build issue in comment above.
Also, please pay attention on unverified commit

**Review by o-kopysov — APPROVED** [review]
LGTM

**Review by m-rudyk — APPROVED** [review]
Approved.

**Pull request merged**
