### PR TITLE
Apply multi-stage builds

### PR DESCRIPTION
**Pull request by tiokim**
# Description

Multi-stage build has been applied because it seemed not good to put the source code into the image.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Build docker images

**Test Configuration**:
* Java: v11
* LPVS Release: v1.x.x

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tiokim** [comment]
@o-kopysov Could you check if the result image is working correctly with MySQL DB?

**Comment by o-kopysov** [comment]
> @o-kopysov Could you check if the result image is working correctly with MySQL DB?

Mykola Rudyk will check LPVS operation.

**Comment by m-rudyk** [comment]
@tiokim , in order to load this container, several changes needs to be applied:

1. application properties (local or global configuration)  with database configuration:
```
# SOSHUB integration
soshub.url=https://test.url

#######################################################################################################
###                             Database configuration                                              ###
#######################################################################################################
# option host.docker.internal is used instead of localhost
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/soshub
spring.datasource.username=<user>
spring.datasource.password=<name>
```

2. Database should be with latest changes (current database_dump.sql file is not modfiied);
3. Some changes in pom.xml in order to prevent startup failure;

In addtion, since we have no ready LPVS database, please keep this PR open until we test solution with 2 containers: 1 for LPVS and 2 for MySQL DB. 

Otherwise, I confirm that applied changes to dockerfile are valid: 
```
docker run -p 7896:7896 --name lpvs lpvs:latest

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.7.10)

06-04-2023 14:24:15.648 [main] INFO  com.lpvs.LicensePreValidationSystem.logStarting - Starting LicensePreValidationSystem v1.0.2 using Java 11.0.16 on 6dac19f5cb4d with PID 1 (/root/lpvs-1.0.2.jar started by root in /root)
06-04-2023 14:24:15.652 [main] INFO  com.lpvs.LicensePreValidationSystem.logStartupProfileInfo - The following 1 profile is active: "local"
06-04-2023 14:24:16.375 [main] INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn - Bootstrapping Spring Data JPA repositories in DEFAULT mode.
06-04-2023 14:24:16.458 [main] INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn - Finished Spring Data repository scanning in 71 ms. Found 5 JPA repository interfaces.
06-04-2023 14:24:17.092 [main] INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize - Tomcat initialized with port(s): 7896 (http)
06-04-2023 14:24:17.108 [main] INFO  org.apache.catalina.core.StandardService.log - Starting service [Tomcat]
06-04-2023 14:24:17.108 [main] INFO  org.apache.catalina.core.StandardEngine.log - Starting Servlet engine: [Apache Tomcat/9.0.73]
06-04-2023 14:24:17.200 [main] INFO  org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].log - Initializing Spring embedded WebApplicationContext
06-04-2023 14:24:17.201 [main] INFO  org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.prepareWebApplicationContext - Root WebApplicationContext: initialization completed in 1480 ms
06-04-2023 14:24:17.507 [main] INFO  org.hibernate.jpa.internal.util.LogHelper.logPersistenceUnitInformation - HHH000204: Processing PersistenceUnitInfo [name: default]
06-04-2023 14:24:17.581 [main] INFO  org.hibernate.Version.logVersion - HHH000412: Hibernate ORM core version 5.6.15.Final
06-04-2023 14:24:17.789 [main] INFO  org.hibernate.annotations.common.Version.<clinit> - HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
06-04-2023 14:24:17.932 [main] INFO  com.zaxxer.hikari.HikariDataSource.getConnection - HikariPool-1 - Starting...
06-04-2023 14:24:18.381 [main] INFO  com.zaxxer.hikari.HikariDataSource.getConnection - HikariPool-1 - Start completed.
06-04-2023 14:24:18.400 [main] INFO  org.hibernate.dialect.Dialect.<init> - HHH000400: Using dialect: org.hibernate.dialect.MySQL8Dialect
06-04-2023 14:24:19.172 [main] INFO  org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator.initiateService - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
06-04-2023 14:24:19.182 [main] INFO  org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.buildNativeEntityManagerFactory - Initialized JPA EntityManagerFactory for persistence unit 'default'
06-04-2023 14:24:19.846 [main] INFO  com.lpvs.service.LPVSLicenseService.init - LICENSES: loaded 558 licenses from DB.
06-04-2023 14:24:19.889 [main] WARN  com.lpvs.service.LPVSLicenseService.init - LICENSES and LICENSE CONFLICTS are not loaded.
06-04-2023 14:24:19.890 [main] ERROR com.lpvs.service.LPVSLicenseService.init - org.springframework.orm.jpa.JpaObjectRetrievalFailureException: Unable to find com.lpvs.entity.LPVSLicense with id 120; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.lpvs.entity.LPVSLicense with id 120
06-04-2023 14:24:20.020 [main] INFO  com.lpvs.service.LPVSDetectService.init - License detection scanner: scanoss
06-04-2023 14:24:20.718 [main] INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start - Tomcat started on port(s): 7896 (http) with context path ''
06-04-2023 14:24:20.728 [main] INFO  com.lpvs.LicensePreValidationSystem.logStarted - Started LicensePreValidationSystem in 5.575 seconds (JVM running for 6.022)
```

**Comment by o-konoval** [comment]
Nice idea to decrease image size!

**Comment by tiokim** [comment]
> @tiokim , in order to load this container, several changes needs to be applied:
> 
> 1. application properties (local or global configuration)  with database configuration:
> 
> ```
> # SOSHUB integration
> soshub.url=https://test.url
> 
> #######################################################################################################
> ###                             Database configuration                                              ###
> #######################################################################################################
> # option host.docker.internal is used instead of localhost
> spring.datasource.url=jdbc:mysql://host.docker.internal:3306/soshub
> spring.datasource.username=<user>
> spring.datasource.password=<name>
> ```
> 
> 2. Database should be with latest changes (current database_dump.sql file is not modfiied);
> 3. Some changes in pom.xml in order to prevent startup failure;
> 
> In addtion, since we have no ready LPVS database, please keep this PR open until we test solution with 2 containers: 1 for LPVS and 2 for MySQL DB. this will be applied to your pr
> 
> Otherwise, I confirm that applied changes to dockerfile are valid:
> 
> ```
> docker run -p 7896:7896 --name lpvs lpvs:latest
> 


@o-kopysov @m-rudyk Please don't forget to implement environment variables for database and update [README.md](https://github.com/Samsung/LPVS/blame/main/README.md#L108).
I look forward to upcoming PRs!

**Pull request closed without merging**
