### PR TITLE
fix: Improve report structure, fix template issue

### PR DESCRIPTION
**Pull request by o-kopysov**
# Pull Request

## Description

Current PR contains improvement of the overall report layout and some template fixes.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code cleanup/refactoring
- [ ] Documentation update
- [ ] This change requires a documentation update
- [ ] CI system update
- [ ] Test Coverage update

## Testing

Local tests passed.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] My code meets the required code coverage for lines (90% and above)
- [X] My code meets the required code coverage for branches (80% and above)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by tdrozdovsky — APPROVED** [review]

**Review by m-rudyk — APPROVED** [review]
I'd recommend to split changes to '/test' and '/src'. For one commit - it is huge change.

**Review by t-naumenko — APPROVED** [review]
LGTM

**Comment by m-rudyk** [comment]
> > I'd recommend to split changes to '/test' and '/src'. For one commit - it is huge change.
> 
> Tests will fail in case of changes in src/ Why do we need PR with a failed build check?

test will fail if different PR's used. I mean - one commit for source another commit for tests.

**Comment by o-kopysov** [comment]
> > > I'd recommend to split changes to '/test' and '/src'. For one commit - it is huge change.
> > 
> > 
> > Tests will fail in case of changes in src/ Why do we need PR with a failed build check?
> 
> test will fail if different PR's used. I mean - one commit for source another commit for tests.

What is the benefit of using such an approach? The reviewer has to review the final code, not the sequence of commits.

**Comment by m-rudyk** [comment]
> > > > I'd recommend to split changes to '/test' and '/src'. For one commit - it is huge change.
> > > 
> > > 
> > > Tests will fail in case of changes in src/ Why do we need PR with a failed build check?
> > 
> > 
> > test will fail if different PR's used. I mean - one commit for source another commit for tests.
> 
> What is the benefit of using such an approach? The reviewer has to review the final code, not the sequence of commits.

it's just recommendation to simplify review. 140+ line in single commit including both source and test (I understand that it is fix) is huge.

**Comment by o-kopysov** [comment]
> > > > > I'd recommend to split changes to '/test' and '/src'. For one commit - it is huge change.
> > > > 
> > > > 
> > > > Tests will fail in case of changes in src/ Why do we need PR with a failed build check?
> > > 
> > > 
> > > test will fail if different PR's used. I mean - one commit for source another commit for tests.
> > 
> > 
> > What is the benefit of using such an approach? The reviewer has to review the final code, not the sequence of commits.
> 
> it's just recommendation to simplify review. 140+ line in single commit including both source and test (I understand that it is fix) is huge.

According to all recommendations that I found, the pull request size is recommended to be less than 200 lines. 
Still, I don't understand why I need to split changes into several commits if the reviewer checks the [final change](https://github.com/Samsung/LPVS/pull/633/files), not the intermediate changes made in commits.

**Comment by m-rudyk** [comment]
> > > > > > I'd recommend to split changes to '/test' and '/src'. For one commit - it is huge change.
> > > > > 
> > > > > 
> > > > > Tests will fail in case of changes in src/ Why do we need PR with a failed build check?
> > > > 
> > > > 
> > > > test will fail if different PR's used. I mean - one commit for source another commit for tests.
> > > 
> > > 
> > > What is the benefit of using such an approach? The reviewer has to review the final code, not the sequence of commits.
> > 
> > 
> > it's just recommendation to simplify review. 140+ line in single commit including both source and test (I understand that it is fix) is huge.
> 
> According to all recommendations that I found, the pull request size is recommended to be less than 200 lines. Still, I don't understand why I need to split changes into several commits if the reviewer checks the [final change](https://github.com/Samsung/LPVS/pull/633/files), not the intermediate changes made in commits.

ok. Let's move this conversation out of this scope.

**Pull request merged**
