### PR TITLE
Change duplicate interfaces between backend and frontend

### LINKED ISSUE #237: Duplicate interfaces between backend and frontend
Due to duplicate interfaces such as '/login' and '/history/*', it is difficult to render the web page when it's refreshed.

### Need to change
**frontend**
- [ ] `login` > `user/login`

**backend** : Add the prefix such as `api/v1/web`
- [ ] `user/info` > `api/v1/web/user/info`
- [ ] `login/check` > `api/v1/web/user/login`
- [ ] `user/update` > `api/v1/web/user/update`
- [ ] `history/{type}/{name}` > `api/v1/web/history/{type}/{name}`

### PR DESCRIPTION
**Pull request by tiokim**
Fixes #237 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code cleanup/refactoring
- [ ] Documentation update
- [ ] This change requires a documentation update
- [ ] CI system update
- [ ] Test Coverage update

# How Has This Been Tested?
1. Place the necessary values to the properties(such as `client-id`, `client-secret` and others) in docker-compose.yml file.
2. Build with `docker compose build` and run the lpvs container with `docker compose up`.
3. Go to http://localhost:7896 on the web browser.
4. Login and access other web pages.

**Test Configuration**:
* Java: v11
* LPVS Release: v1.x.x

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tiokim** [comment]
@kyudori Can you verify if this PR seems okay?

**Comment by kyudori** [comment]
> @kyudori Can you verify if this PR seems okay?

I checked that the F5 (refresh) error has been resolved. 
And also, LPVS and front end are working correctly.
There seems to be no problem with this Pull Request.

- GitHub ID: `kyudori`, Option: `My Pull Request`


- GitHub ID: `kyudori`, Option: `My Repository Pull Request`


- GitHub ID: `hwan5180`, Option: `My Repository Pull Request`


- GitHub ID: `hwan5180`, Option: `My Repository Pull Request`

**Review by o-kopysov — APPROVED** [review]
LGTM

**Review by MoonkiHong — APPROVED** [review]
+1

**Pull request merged**
