### PR TITLE
`LicenseService`, 5 methods tests

### PR DESCRIPTION
**Pull request by namefreezers**
# Description

Added unit test set for the `com.lpvs.service.LicenseService` class. This step is required for the GitHub action infra setup.

Wait for 2 bugfix PRs, then test set will pass

## Type of change

- [x] Test Coverage update

# How Has This Been Tested?
mvn clean install
mvn test

**Test Configuration**:
* Java: v18
* LPVS Release: v1.0.0

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by namefreezers** [comment]
Tests will pass after (and if) 2 bugfix pull-requests will be merged

**Comment by o-kopysov** [comment]
Please rebase your code. I've merged 2 bug fixes to main branch.

**Review by o-kopysov — APPROVED** [review]
LGTM

**Review by MoonkiHong — APPROVED** [review]
+1

**Pull request merged**
