### PR TITLE
feat: Adding automatic release generation

### PR DESCRIPTION
**Pull request by tdrozdovsky**
# Pull Request

## Description

Adding automatic generation of releases, uploading of release artifacts, etc

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] CI system update

## Testing

After push any tag "v*" see to Release

**Test Configuration**:
* Java: v11
* LPVS Release: v1.x.x

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] My code meets the required code coverage for lines (90% and above)
- [ ] My code meets the required code coverage for branches (80% and above)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by o-kopysov — APPROVED** [review]
LGTM

**Comment by tiokim** [comment]
What about merging `publish-jar.yml`, `publish-docker-img.yml` and this into one?

**Comment by tdrozdovsky** [comment]
> What about merging `publish-jar.yml`, `publish-docker-img.yml` and this into one?



> What about merging `publish-jar.yml`, `publish-docker-img.yml` and this into one?

Great idea, I will do it in the next release.  now I want to be sure that these changes works correctly

**Comment by o-kopysov** [comment]
> > What about merging `publish-jar.yml`, `publish-docker-img.yml` and this into one?
> 
> Great idea, I will do it in the next release. now I want to be sure that these changes works correctly

Corresponding ticket is created #365

**Review by o-konoval — APPROVED** [review]
Good job, approved!

**Review by m-rudyk — APPROVED** [review]
Approved.

**Review by tiokim — APPROVED** [review]
LGTM

**Pull request merged**
